### PR TITLE
Update default release ver

### PR DESCRIPTION
**Pull request by jkonecny12**
Default releasever pointing to new Rawhide (releasever 29).

I can remove the documentation commit if you want to do it yourself.

**DO NOT MERGE BEFORE BRANCHING**

### CODE REVIEW

**Comment by jkonecny12** [comment]
From my understanding branching was already done and this can be merged. However, I'm not sure where everywhere are those releasever used, so my advice is to test it before merge.

**Comment by bcl** [comment]
I'm not quite ready to branch yet, we keep running into things that'll effect f28. Once that settles down then it will be ok to update all of these. Thanks!

**Comment by jkonecny12** [comment]
ping, any changes on this?

**Comment by bcl** [comment]
Probably this week. I have some changes to make to the docs page so we can host docs for other branches so I'll likely branch and merge this first.

**Comment by bcl** [comment]
I've now branched for f28, and pulled in your version number changes. I'm working on some doc changes so that we can support multiple doc versions on https://rhinstaller.github.io/lorax/ so I skipped the doc rebuild commit. Thanks!

**Pull request closed without merging**
