### PR TITLE
Add compression args to installimg template command

### PR DESCRIPTION
**Pull request by bcl**

### CODE REVIEW

**Comment by dashea** [comment]
Two things:

Seems like compression args without a leading - should raise a ValueError instead of being silently dropped.

Where does 3700MiB come from? I thought 32-bit processes were limited to 3G of address space to leave room for kernel addresses.

**Comment by bcl** [comment]
The example comes from dgilmore, that's what they use when running pungi on them.

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by bcl** [comment]
Pushed to master and F24, need to backport to F23 and F22.

**Comment by bcl** [comment]
Pushed everywhere.

**Pull request closed without merging**
