### PR TITLE
Added option to remove packages (parallel to installpkgs)

### PR DESCRIPTION
**Pull request by jcpunk**
The code to do removals already existed, I've just added a command line switch to manipulate it.  The end behavior is basically the same as installpkgs, only it removes them instead.

### CODE REVIEW

**Comment by cgwalters** [comment]
Why?

**Comment by jcpunk** [comment]
I'd use this for much the same reason as installpkgs.

The EL7 default template is almost good enough for my needs.  I just don't want this one package installed in the media.  This switch allows me to directly use the official template while automating my one small change.

**Comment by cgwalters** [comment]
Can you say what that one package is?

**Comment by jcpunk** [comment]
My specific usage is with subscription-manager.  For SL, we don't use it so having it on the media just results in creating some redhat.repo files in /etc/ that aren't owned by anything.

**Comment by cgwalters** [comment]
Thanks!  That's the kind of thing I think belongs in commit messages, but it's ok to have here too :smile: 

The patch seems sane to me.  I'm not a lorax committer though.

**Pull request merged**
