### PR TITLE
Add ntp configuration file to installation

### PR DESCRIPTION
**Pull request by jkonecny12**
Add package ntp and remove it except ntp.conf file.

Related: rhbz#1085013

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by bcl** [comment]
I don't understand how this solved the problem in the bug. Adding the ntp.conf to the install image isn't going to have any effect on the packages installed to their system.

**Comment by jkonecny12** [comment]
@bcl you must look on main commit for this patch in this [PR](https://github.com/rhinstaller/anaconda/pull/144). 
Here I add configuration file to install environment and in that PR the servers are changed and they are copied to the installed system.

Sorry I mentioned this in the second PR and I forgot to add it here too.

**Comment by bcl** [comment]
Thanks for the explanation, could you add that to the commit before pushing?

**Comment by jkonecny12** [comment]
OK, I will add some information to commit message.

**Comment by jkonecny12** [comment]
Merging this commit.
Thank you all for help.

**Pull request merged**
