### PR TITLE
Add enough of shadow-utils to create new user accounts.

### PR DESCRIPTION
**Pull request by dashea**
Yes user accounts, some account management

### CODE REVIEW

**Comment by vpodzime** [comment]
Looks good to me.

**Comment by bcl** [comment]
Why do we need these here? This is for the libuser replacement, right? Shouldn't any tools it is using be run from the installed system's chroot? Sorry for all the ? marks :)

**Comment by dashea** [comment]
> Shouldn't any tools it is using be run from the installed system's chroot?

Sort of. The way I did the anaconda change was to run useradd etc from / with -R <sysroot>, so the tools themselves are doing the chroot instead of anaconda. Granted, we add the sysroot to the path so that could still use the tools installed to the sysroot, but I figured that shadow-utils is probably one of those base packages that the cloud folks don't install to their images, and I did this change to avoid breaking things for that case.

**Comment by bcl** [comment]
Ok, ACK from me as well then, thanks.

**Comment by dashea** [comment]
Pushed to f23 and master

**Pull request closed without merging**
