### PR TITLE
Create UDF iso when stage2 is >= 4GiB (#1312158)

### PR DESCRIPTION
**Pull request by bcl**
Some images are becoming REALLY large. When a file is >= 4GiB we need to
pass -allow-limited-size to mkisofs to tell it to make a UDF image. Note
that the manpage says that this may result in it not booting on all
systems.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Looks good to me.

**Comment by vpodzime** [comment]
I have the same concern that @dwlehman had yesterday on IRC -- what about blivet and UDF? (didn't manage to wait for the answer, sorry).

**Comment by bcl** [comment]
Blivet doesn't care that it is UDF. It actually doesn't even mention it in the logs, and it properly detects it as a cdrom and as the backing device, setting it as protected. I can start an install with it and it gets past partitioning and running rsync, then crashes for other reasons.

Also note that this is only for live images with squashfs.img >= 4GiB so it isn't going to show up everywhere, only in spins that are really large.

**Comment by vpodzime** [comment]
Works for me then. Thanks for the extra info.

**Comment by bcl** [comment]
Pushed.

**Pull request closed without merging**
